-- Create missing tables for the application
-- This script creates the required tables for payment_details, questionnaire_details, and user_dashboard

-- Create payment_details table
CREATE TABLE IF NOT EXISTS payment_details (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    user_uuid VARCHAR(255),
    user_email VARCHAR(255) NOT NULL,
    user_name VARCHAR(255),
    plan_name_payment VARCHAR(255),
    original_price DECIMAL(10,2),
    discount_amount DECIMAL(10,2),
    final_price DECIMAL(10,2),
    currency VARCHAR(3) DEFAULT 'USD',
    coupon_code VARCHAR(255),
    coupon_applied BOOLEAN DEFAULT FALSE,
    coupon_message TEXT,
    payment_method VARCHAR(50),
    payment_provider VARCHAR(50),
    payment_status VARCHAR(50) DEFAULT 'pending',
    transaction_id VARCHAR(255),
    transaction_hash VARCHAR(255),
    crypto_currency VARCHAR(10),
    crypto_address VARCHAR(255),
    crypto_verification_status VARCHAR(50) DEFAULT 'pending',
    crypto_transaction_hash VARCHAR(255),
    crypto_from_address VARCHAR(255),
    crypto_amount VARCHAR(50),
    billing_country VARCHAR(100),
    billing_city VARCHAR(100),
    payment_data JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create questionnaire_details table
CREATE TABLE IF NOT EXISTS questionnaire_details (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    user_uuid VARCHAR(255),
    user_email VARCHAR(255) NOT NULL,
    user_name VARCHAR(255),
    trades_per_day VARCHAR(50),
    trading_session VARCHAR(50),
    preferred_trading_hours VARCHAR(100),
    crypto_assets JSONB,
    forex_assets JSONB,
    custom_forex_pairs JSONB,
    has_account VARCHAR(10),
    account_equity DECIMAL(15,2),
    prop_firm VARCHAR(255),
    account_type VARCHAR(100),
    account_size DECIMAL(15,2),
    account_number VARCHAR(100),
    account_currency VARCHAR(10) DEFAULT 'USD',
    broker_name VARCHAR(255),
    broker_platform VARCHAR(255),
    risk_percentage DECIMAL(5,2),
    risk_reward_ratio VARCHAR(20),
    custom_risk_reward_ratio VARCHAR(20),
    max_daily_loss_percentage DECIMAL(5,2),
    max_weekly_loss_percentage DECIMAL(5,2),
    max_monthly_loss_percentage DECIMAL(5,2),
    trading_experience VARCHAR(50),
    trading_goals TEXT,
    trading_style VARCHAR(50),
    preferred_markets VARCHAR(100),
    risk_tolerance VARCHAR(50),
    volatility_tolerance VARCHAR(50),
    drawdown_tolerance VARCHAR(50),
    emotional_control VARCHAR(50),
    discipline_level VARCHAR(50),
    stress_management VARCHAR(50),
    additional_notes TEXT,
    marketing_consent BOOLEAN DEFAULT FALSE,
    terms_accepted BOOLEAN DEFAULT FALSE,
    privacy_policy_accepted BOOLEAN DEFAULT FALSE,
    completion_percentage INTEGER DEFAULT 0,
    is_completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id)
);

-- Create user_dashboard table
CREATE TABLE IF NOT EXISTS user_dashboard (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    user_uuid VARCHAR(255),
    user_email VARCHAR(255) NOT NULL,
    user_name VARCHAR(255),
    current_equity DECIMAL(15,2),
    initial_equity DECIMAL(15,2),
    total_pnl DECIMAL(15,2),
    pnl_percentage DECIMAL(5,2),
    win_rate DECIMAL(5,2),
    total_trades INTEGER,
    winning_trades INTEGER,
    losing_trades INTEGER,
    average_win DECIMAL(15,2),
    average_loss DECIMAL(15,2),
    profit_factor DECIMAL(10,2),
    max_drawdown DECIMAL(15,2),
    current_drawdown DECIMAL(15,2),
    gross_profit DECIMAL(15,2),
    gross_loss DECIMAL(15,2),
    consecutive_wins INTEGER,
    consecutive_losses INTEGER,
    current_streak INTEGER,
    best_streak INTEGER,
    worst_streak INTEGER,
    risk_reward_ratio DECIMAL(10,2),
    sharpe_ratio DECIMAL(10,2),
    sortino_ratio DECIMAL(10,2),
    calmar_ratio DECIMAL(10,2),
    recovery_factor DECIMAL(10,2),
    expectancy DECIMAL(10,2),
    kelly_percentage DECIMAL(5,2),
    optimal_f DECIMAL(10,2),
    account_balance DECIMAL(15,2),
    free_margin DECIMAL(15,2),
    margin_level DECIMAL(10,2),
    used_margin DECIMAL(15,2),
    leverage INTEGER,
    daily_pnl DECIMAL(15,2),
    weekly_pnl DECIMAL(15,2),
    monthly_pnl DECIMAL(15,2),
    yearly_pnl DECIMAL(15,2),
    last_trade_time TIMESTAMP,
    last_update_time TIMESTAMP,
    trading_session VARCHAR(50),
    market_condition VARCHAR(50),
    volatility_level VARCHAR(50),
    trend_direction VARCHAR(50),
    support_level DECIMAL(15,2),
    resistance_level DECIMAL(15,2),
    pivot_point DECIMAL(15,2),
    fibonacci_levels JSONB,
    moving_averages JSONB,
    rsi DECIMAL(5,2),
    macd JSONB,
    bollinger_bands JSONB,
    stochastic JSONB,
    williams_r DECIMAL(5,2),
    cci DECIMAL(5,2),
    atr DECIMAL(15,2),
    adx DECIMAL(5,2),
    obv DECIMAL(15,2),
    vwap DECIMAL(15,2),
    ichimoku JSONB,
    elliott_wave JSONB,
    harmonic_patterns JSONB,
    chart_patterns JSONB,
    candlestick_patterns JSONB,
    volume_profile JSONB,
    order_flow JSONB,
    market_depth JSONB,
    time_and_sales JSONB,
    level_2_data JSONB,
    news_sentiment VARCHAR(50),
    economic_calendar JSONB,
    central_bank_announcements JSONB,
    earnings_calendar JSONB,
    dividend_calendar JSONB,
    options_flow JSONB,
    dark_pool_activity JSONB,
    insider_trading JSONB,
    institutional_flow JSONB,
    retail_sentiment VARCHAR(50),
    social_sentiment VARCHAR(50),
    fear_greed_index INTEGER,
    vix DECIMAL(5,2),
    put_call_ratio DECIMAL(5,2),
    implied_volatility DECIMAL(5,2),
    term_structure JSONB,
    skew DECIMAL(10,2),
    kurtosis DECIMAL(10,2),
    correlation_matrix JSONB,
    beta DECIMAL(10,2),
    alpha DECIMAL(10,2),
    tracking_error DECIMAL(10,2),
    information_ratio DECIMAL(10,2),
    treynor_ratio DECIMAL(10,2),
    jensen_alpha DECIMAL(10,2),
    modigliani_ratio DECIMAL(10,2),
    sterling_ratio DECIMAL(10,2),
    burke_ratio DECIMAL(10,2),
    kappa_3_ratio DECIMAL(10,2),
    gain_to_pain_ratio DECIMAL(10,2),
    profit_to_max_drawdown DECIMAL(10,2),
    calmar_ratio_annualized DECIMAL(10,2),
    sterling_ratio_annualized DECIMAL(10,2),
    burke_ratio_annualized DECIMAL(10,2),
    kappa_3_ratio_annualized DECIMAL(10,2),
    gain_to_pain_ratio_annualized DECIMAL(10,2),
    profit_to_max_drawdown_annualized DECIMAL(10,2),
    theme VARCHAR(50),
    layout_preferences JSONB,
    widget_settings JSONB,
    chart_settings JSONB,
    alert_settings JSONB,
    notification_settings JSONB,
    risk_settings JSONB,
    trading_settings JSONB,
    real_time_data JSONB,
    last_signal JSONB,
    market_status VARCHAR(50),
    connection_status VARCHAR(50),
    open_positions JSONB,
    trade_history JSONB,
    signals JSONB,
    dashboard_layout JSONB,
    last_activity TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_payment_details_user_id ON payment_details(user_id);
CREATE INDEX IF NOT EXISTS idx_payment_details_user_email ON payment_details(user_email);
CREATE INDEX IF NOT EXISTS idx_payment_details_created_at ON payment_details(created_at);

CREATE INDEX IF NOT EXISTS idx_questionnaire_details_user_id ON questionnaire_details(user_id);
CREATE INDEX IF NOT EXISTS idx_questionnaire_details_user_email ON questionnaire_details(user_email);

CREATE INDEX IF NOT EXISTS idx_user_dashboard_user_id ON user_dashboard(user_id);
CREATE INDEX IF NOT EXISTS idx_user_dashboard_user_email ON user_dashboard(user_email);
CREATE INDEX IF NOT EXISTS idx_user_dashboard_updated_at ON user_dashboard(updated_at);

-- Add comments to tables
COMMENT ON TABLE payment_details IS 'Stores payment information for user subscriptions and purchases';
COMMENT ON TABLE questionnaire_details IS 'Stores user questionnaire responses for trading preferences and risk management';
COMMENT ON TABLE user_dashboard IS 'Stores user dashboard data including trading performance metrics and preferences';
